"""
=================================================
File: components.py

Purpose:
Reusable UI components for the AI SQL Analytics
Assistant.

Author: Vidhyalakshmi
Project: AI SQL Analytics Assistant
=================================================
"""

import pandas as pd
import streamlit as st


def render_question_input() -> str:
    """
    Render the natural language question input.

    Returns:
        User's question.
    """

    st.subheader("💬 Ask a Business Question")

    question = st.text_area(
        label="Business Question",
        placeholder=(
            "Example:\n"
            "Show the top 10 customers by revenue."
        ),
        height=120,
        label_visibility="collapsed"
    )

    return question


def render_generate_button() -> bool:
    """
    Render the Generate Report button.

    Returns:
        True when clicked.
    """

    return st.button(
        "🚀 Generate Report",
        use_container_width=True
    )


def render_success_message():
    """
    Display success message.
    """

    st.success(
        "Query executed successfully!"
    )


def render_dataframe(
    dataframe: pd.DataFrame
):
    """
    Display query results.
    """

    st.dataframe(
        dataframe,
        use_container_width=True
    )

def render_download_button(
    dataframe: pd.DataFrame
):
    """
    Provide a download button for query results.
    """

    csv_data = dataframe.to_csv(
        index=False
    )

    st.download_button(
        label="⬇️ Download Results as CSV",
        data=csv_data,
        file_name="query_results.csv",
        mime="text/csv"
    )
    

def render_sql(sql: str):
    """
    Display the SQL generated by Gemini.
    """

    st.code(
        sql,
        language="sql"
    )


def render_result_summary(dataframe: pd.DataFrame):
    """
    Display basic information about query results.
    """

    st.caption(
        f"Rows returned: {len(dataframe):,}"
    )


def render_chart(figure):
    """
    Display a Plotly chart in Streamlit.

    Responsibility:
    Render the supplied Plotly figure.
    """

    if figure is None:
        st.info(
            "No suitable chart could be generated for this result."
        )
        return

    st.plotly_chart(
        figure,
        use_container_width=True
    )

def render_insight(
    insight: str
):
    """
    Render the generated business insight.
    """

    st.markdown(
        insight
    )


def render_error_message(
    message: str
):
    """
    Display an error message.
    """

    st.error(
        message
    )


def render_warning_message(
    message: str
):
    """
    Display a warning message.
    """

    st.warning(
        message
    )
    

def render_footer():
    st.markdown(
        """
        <div style="text-align: center; margin-top: 40px; padding: 15px 0;">
            <p style="margin: 0; font-size: 14px;">
                <strong>AI SQL Analytics Assistant</strong>
            </p>
            <p style="margin: 4px 0 0 0; font-size: 13px;">
                Portfolio Project · Vidhyalakshmi A
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )